version: '3'
name: fast_api_crud

volumes:
  pg_data:

services:
  db:
    container_name: db
    image: postgres:13.10
    env_file: ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

  app:
    container_name: app
    build: 
      context: ../
      dockerfile: ./docker/Dockerfile
    command: >
      sh -c "alembic upgrade head &&
             python -m debugpy --listen 0:5678 -m uvicorn app.main:app --host 0.0.0.0  --port 8000 --reload"
    env_file: ../.env
    volumes:
      - ../:/app
    depends_on:
      - db
    ports:
      - 5678:5678
      - 8000:8000
    restart: always
