"""Модуль для создания констант."""

CATEGORY_NAME_MAX_LENGTH = 64

PRODUCT_NAME_MAX_LENGTH = 64
PRODUCT_IMAGE_URL_MAX_LENGTH = 128

SLUG_REGEXP = r'^[a-z0-9\-]{1,64}$'

USER_FIRST_NAME_MAX_LENGTH = 64
USER_LAST_NAME_MAX_LENGTH = 64
USER_EMAIL_MAX_LENGTH = 64
USER_PASSWORD_MAX_LENGTH = 64
USER_USERNAME_REGEXP = r'^[\w.\-]{1,64}$'
